# Generated by Django 5.1.4 on 2025-02-11 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('experiencia', models.PositiveIntegerField(default=0)),
                ('patente', models.CharField(choices=[('INICIANTE', 'Iniciante em Energia'), ('APRENDIZ', 'Aprendiz da Eficiência'), ('TECNICO', 'Técnico em Economia'), ('ENGENHEIRO', 'Engenheiro da Energia'), ('ESPECIALISTA', 'Especialista em Eficiência'), ('MESTRE', 'Mestre da Energia'), ('DOUTOR', 'Doutor em Sustentabilidade'), ('LENDA', 'Lenda da Eficiência')], default='INICIANTE', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('passos_necessarios', models.PositiveIntegerField(default=1)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('passo1', models.TextField(blank=True, null=True)),
                ('passo2', models.TextField(blank=True, null=True)),
                ('passo3', models.TextField(blank=True, null=True)),
                ('passo4', models.TextField(blank=True, null=True)),
                ('equipamentos', models.ManyToManyField(related_name='tarefas', to='dashboard.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='UserEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.equipamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passos_concluidos', models.PositiveIntegerField(default=0)),
                ('completo', models.BooleanField(default=False)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
