# Generated by Django 5.1.4 on 2025-02-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desafio',
            name='html_guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
