# Generated by Django 5.1.4 on 2025-02-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_usertarefa_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoDicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
            ],
        ),
    ]
