# Generated by Django 5.1.4 on 2025-02-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userdesafio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desafio',
            old_name='html_guide',
            new_name='passo1',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='completo',
        ),
        migrations.AddField(
            model_name='desafio',
            name='passo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='passo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='passo4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='pontos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdesafio',
            name='passos_concluidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
