# Generated by Django 5.1.4 on 2025-02-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_html_guide_desafio_passo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='passos_necessarios',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
