# Generated by Django 5.1.4 on 2025-02-07 23:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_userdesafio_unique_together_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='PerfilGamer',
        ),
    ]
