# Generated by Django 5.1.4 on 2025-02-07 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_perfil_perfilgamer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trofeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='trofeus/')),
                ('requisito', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='perfilgamer',
            name='experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilgamer',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='perfilgamer',
            name='patente',
            field=models.CharField(choices=[('INICIANTE', 'Iniciante em Energia'), ('APRENDIZ', 'Aprendiz da Eficiência'), ('TECNICO', 'Técnico em Economia'), ('ENGENHEIRO', 'Engenheiro da Energia'), ('ESPECIALISTA', 'Especialista em Eficiência'), ('MESTRE', 'Mestre da Energia'), ('DOUTOR', 'Doutor em Sustentabilidade'), ('LENDA', 'Lenda da Eficiência')], default='INICIANTE', max_length=50),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_total', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pontuacao_total'],
            },
        ),
        migrations.AddField(
            model_name='perfilgamer',
            name='trofeus',
            field=models.ManyToManyField(blank=True, to='dashboard.trofeu'),
        ),
    ]
