# Generated by Django 5.1.4 on 2025-02-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_trofeu_perfilgamer_experiencia_perfilgamer_nivel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
