# Generated by Django 5.1.4 on 2025-02-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilgamer',
            name='pontos',
        ),
    ]
