# Generated by Django 5.1.3 on 2024-11-22 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personalizado', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('geladeira', 'Geladeira'), ('tv', 'TV'), ('ar_condicionado', 'Ar Condicionado'), ('maquina_lavar', 'Máquina de Lavar'), ('microondas', 'Micro-ondas'), ('computador', 'Computador'), ('chuveiro_eletrico', 'Chuveiro Elétrico'), ('ventilador', 'Ventilador'), ('forno_eletrico', 'Forno Elétrico'), ('luminaria_led', 'Luminária LED'), ('ferro_passar', 'Ferro de Passar')], max_length=50)),
                ('potencia', models.PositiveIntegerField()),
                ('horas_por_dia', models.PositiveIntegerField()),
                ('tarifa_por_kwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumoMensalKwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custoMensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
