# Generated by Django 5.1.3 on 2024-11-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_estabelecimento_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='features.estabelecimento'),
        ),
    ]
