# Generated by Django 5.1.4 on 2025-02-11 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumomensal',
            unique_together={('usuario', 'mes', 'ano')},
        ),
        migrations.AddField(
            model_name='userperfil',
            name='cupom',
            field=models.CharField(blank=True, help_text='Cupom de desconto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consumomensal',
            name='ano',
            field=models.IntegerField(default=1, help_text='Ano do consumo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumomensal',
            name='mes',
            field=models.IntegerField(default=1, help_text='Mês do consumo (1-12)'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='consumomensal',
            name='cupom',
        ),
    ]
