# Generated by Django 5.1.4 on 2025-02-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='cupom',
            field=models.CharField(blank=True, help_text='Cupom de desconto', max_length=20, null=True),
        ),
    ]
