# Generated by Django 5.1.4 on 2025-02-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pontos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
