# Generated by Django 5.1.4 on 2025-02-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pontos',
        ),
    ]
