# Generated by Django 5.1.4 on 2025-02-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userperfil_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='ultimo_consumo_registrado',
            field=models.FloatField(default=0, help_text='Último consumo registrado'),
        ),
    ]
