# Generated by Django 5.1.4 on 2025-02-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userperfil_ultimo_consumo_registrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mês do consumo (1-12)')),
                ('ano', models.IntegerField(help_text='Ano do consumo')),
                ('consumo', models.FloatField(help_text='Consumo em kWh')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='user.userperfil')),
            ],
            options={
                'unique_together': {('perfil', 'mes', 'ano')},
            },
        ),
    ]
