# Generated by Django 5.1.4 on 2025-02-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userperfil_cupom_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='cupom',
            field=models.ForeignKey(blank=True, help_text='Cupom associado ao usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_perfil', to='user.cupom'),
        ),
    ]
