# Generated by Django 5.1.4 on 2025-02-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userperfil_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='perfil_fotos/'),
        ),
    ]
