# Generated by Django 5.1.4 on 2025-02-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_cupom_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumomensal',
            name='mes',
            field=models.IntegerField(help_text='Mês do consumo (1-12)', unique=True),
        ),
    ]
