# Generated by Django 5.1.4 on 2025-02-11 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_consumomensal_mes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoConsumo',
        ),
    ]
