# Generated by Django 5.1.4 on 2025-02-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_historicoconsumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperfil',
            name='cupom',
        ),
    ]
