# Generated by Django 5.1.4 on 2025-02-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userperfil_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumomensal',
            name='mes',
            field=models.IntegerField(help_text='Mês do consumo (1-12)'),
        ),
    ]
