# Generated by Django 5.1.4 on 2025-02-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_consumomensal_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='conta_contrato',
            field=models.IntegerField(default=1234, max_length=12),
            preserve_default=False,
        ),
    ]
