# Generated by Django 5.1.4 on 2024-12-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personalizado', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('geladeira', 'Geladeira'), ('tv', 'TV'), ('ar_condicionado', 'Ar Condicionado'), ('maquina_lavar', 'Máquina de Lavar'), ('microondas', 'Micro-ondas'), ('computador', 'Computador'), ('chuveiro_eletrico', 'Chuveiro Elétrico'), ('ventilador', 'Ventilador'), ('forno_eletrico', 'Forno Elétrico'), ('luminaria_led', 'Luminária LED'), ('ferro_passar', 'Ferro de Passar')], max_length=50)),
                ('potencia', models.PositiveIntegerField()),
                ('horas_por_dia', models.PositiveIntegerField()),
                ('tarifa_por_kwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumoMensalKwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custoMensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='functionalities.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functionalities.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_gasto_mensal', models.DecimalField(decimal_places=2, help_text='Meta de gasto mensal em reais', max_digits=10)),
                ('meta_consumo_mensal', models.DecimalField(decimal_places=2, help_text='Meta de consumo mensal em kWh (opcional)', max_digits=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('estabelecimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planos_economia', to='functionalities.estabelecimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
