# Generated by Django 5.1.3 on 2024-11-25 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoEconomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_gasto_mensal', models.DecimalField(decimal_places=2, help_text='Meta de gasto mensal em reais', max_digits=10)),
                ('meta_consumo_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Meta de consumo mensal em kWh (opcional)', max_digits=10, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_economia', to='functionalities.estabelecimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
