# Generated by Django 5.1.3 on 2024-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0007_equipamento_posicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='posicao',
        ),
        migrations.AddField(
            model_name='planoeconomia',
            name='posicao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
