# Generated by Django 5.1.3 on 2024-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0008_remove_equipamento_posicao_planoeconomia_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoeconomia',
            name='meta_consumo_mensal',
            field=models.DecimalField(decimal_places=2, help_text='Meta de consumo mensal em kWh (opcional)', max_digits=10),
        ),
    ]
