# Generated by Django 5.1.3 on 2024-11-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0009_alter_planoeconomia_meta_consumo_mensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functionalities.estabelecimento')),
            ],
        ),
    ]
